#!/bin/bash
#
# evaluate-session.sh — Deterministic Meta-Improvement (Context7 Pattern)
#
# Triggered: Stop hook (every session end)
# Purpose: Evaluate session, crystallize patterns, update SCRUM/Gantt
#
# 逆水行舟，不进则退 — No advance is to drop back
#

set -e

# Find project root
find_project_root() {
    local dir="${1:-$PWD}"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/CLAUDE.md" ] || [ -f "$dir/.remembrance" ]; then
            echo "$dir"
            return
        fi
        dir=$(dirname "$dir")
    done
    echo "$PWD"
}

PROJECT_ROOT=$(find_project_root)
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$PROJECT_ROOT/plugin}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Observability paths
OBS_DIR="$PROJECT_ROOT/.observability"
LOOP_STATE="$PROJECT_ROOT/.loop-state.yaml"
REMEMBRANCE="$PROJECT_ROOT/.remembrance"
SCRUM="$PROJECT_ROOT/scrum/SCRUM.md"

mkdir -p "$OBS_DIR"

echo "--- Meta-Improvement: Session Evaluation ---"

# ============================================
# STEP 1: Count session changes
# ============================================
echo "1. Auditing session changes..."

# Count new .remembrance entries (compare with last snapshot)
LAST_ENTRY_COUNT=$(grep -c "^timestamp:" "$REMEMBRANCE" 2>/dev/null || echo 0)
LAST_SHAPESHIFTS=$(grep -c "shape_shift: true" "$REMEMBRANCE" 2>/dev/null || echo 0)

# Count modified files in git
MODIFIED_FILES=$(git -C "$PROJECT_ROOT" diff --name-only HEAD 2>/dev/null | wc -l | tr -d ' ')

echo "   Entries: $LAST_ENTRY_COUNT | Shape shifts: $LAST_SHAPESHIFTS | Modified files: $MODIFIED_FILES"

# ============================================
# STEP 2: Determine loop phase
# ============================================
echo "2. Determining loop continuation point..."

if [ -f "$LOOP_STATE" ]; then
    CURRENT_PHASE=$(grep "phase:" "$LOOP_STATE" 2>/dev/null | head -1 | cut -d: -f2 | tr -d ' ')
else
    CURRENT_PHASE="OBSERVE"
fi

# Advance phase: OBSERVE → DECIDE → ACT → LEARN → continue
case "$CURRENT_PHASE" in
    OBSERVE) NEXT_PHASE="DECIDE" ;;
    DECIDE)  NEXT_PHASE="ACT" ;;
    ACT)     NEXT_PHASE="LEARN" ;;
    LEARN)   NEXT_PHASE="OBSERVE" ;;
    *)       NEXT_PHASE="OBSERVE" ;;
esac

echo "   Current: $CURRENT_PHASE → Next: $NEXT_PHASE"

# ============================================
# STEP 3: Update loop state
# ============================================
echo "3. Persisting loop state..."

cat > "$LOOP_STATE" << EOF
# Loop State — Auto-generated by meta-improvement
# 不进则退 — The loop never stops

phase: $NEXT_PHASE
last_phase: $CURRENT_PHASE
timestamp: $TIMESTAMP
session:
  truths: $LAST_ENTRY_COUNT
  shape_shifts: $LAST_SHAPESHIFTS
  files_modified: $MODIFIED_FILES
continuation:
  file: .loop-state.yaml
  remembrance: $REMEMBRANCE
  scrum: $SCRUM
next_action: |
  Read .remembrance, continue from $NEXT_PHASE phase
  Check SCRUM.md for alpha state transitions
EOF

echo "   Saved: $LOOP_STATE"

# ============================================
# STEP 4: Update observability tracker
# ============================================
echo "4. Updating observability..."

# Update remembrance tracker
TRACKER_FILE="$OBS_DIR/remembrance-tracker.json"
if [ -f "$TRACKER_FILE" ]; then
    # Update read_count and last_read
    TMP_FILE=$(mktemp)
    jq --arg ts "$TIMESTAMP" --arg count "$LAST_ENTRY_COUNT" --arg shifts "$LAST_SHAPESHIFTS" '
        .last_read = $ts |
        .read_count = (.read_count + 1) |
        .reads += [{
            "timestamp": $ts,
            "agent": "meta-improvement",
            "context": "session-end-evaluation",
            "truths_seen": ($count | tonumber),
            "shape_shifts_seen": ($shifts | tonumber),
            "delta_since_last": "session",
            "reminder_chain": (.reads | length + 1)
        }]
    ' "$TRACKER_FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$TRACKER_FILE"
fi

# ============================================
# STEP 5: Check SCRUM alpha transitions
# ============================================
echo "5. Checking SCRUM alpha states..."

if [ -f "$SCRUM" ]; then
    # Count checked items
    WORK_ITEMS=$(grep -c "\[x\]" "$SCRUM" 2>/dev/null || echo 0)
    echo "   Completed checkpoints: $WORK_ITEMS"
fi

# ============================================
# STEP 6: Generate continuation summary
# ============================================
echo ""
echo "=== Session Summary ==="
echo "Phase:        $CURRENT_PHASE → $NEXT_PHASE"
echo "Truths:       $LAST_ENTRY_COUNT (${LAST_SHAPESHIFTS} shifts)"
echo "Files:        $MODIFIED_FILES modified"
echo "Continuation: Read .loop-state.yaml on next session"
echo ""
echo "不进则退 — Keep moving forward"
echo "========================"
